from __future__ import annotations

import getpass
import os
import re
import tempfile
from collections.abc import Callable
from pathlib import Path

from .config import read_dotenv

PROVIDERS = {
    "openai": ("OpenAI / Codex", "OPENAI_API_KEY", "gpt-5"),
    "grok": ("xAI Grok", "XAI_API_KEY", "grok-4"),
    "claude": ("Anthropic Claude", "ANTHROPIC_API_KEY", "claude-sonnet-4-5"),
    "gemini": ("Google Gemini", "GEMINI_API_KEY", "gemini-2.5-pro"),
}
SAFE_VALUE = re.compile(r"^[A-Za-z0-9._:/,-]*$")


def _choose_provider(
    input_fn: Callable[[str], str], output_fn: Callable[[str], None]
) -> str:
    output_fn("\nChoose a model provider / 모델 공급자를 선택하세요:")
    names = list(PROVIDERS)
    for index, name in enumerate(names, 1):
        output_fn(f"  {index}. {PROVIDERS[name][0]} ({name})")
    while True:
        answer = input_fn("Provider [1]: ").strip() or "1"
        if answer in PROVIDERS:
            return answer
        if answer.isdigit() and 1 <= int(answer) <= len(names):
            return names[int(answer) - 1]
        output_fn("Enter 1-4 or a provider name / 1-4 또는 공급자 이름을 입력하세요.")


def _safe_value(value: str, label: str) -> str:
    if not SAFE_VALUE.fullmatch(value):
        raise ValueError(f"{label} contains unsupported characters")
    return value


def _write_config(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    os.chmod(path.parent, 0o700)
    lines = ["# Generated by `lemono setup`. Do not commit this file."]
    lines.extend(f"{key}={value}" for key, value in sorted(values.items()) if value)
    content = "\n".join(lines) + "\n"
    file_descriptor, temporary_name = tempfile.mkstemp(prefix=".env.", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_path, 0o600)
        temporary_path.replace(path)
    finally:
        temporary_path.unlink(missing_ok=True)


def run_setup(
    *,
    config_path: Path | None = None,
    input_fn: Callable[[str], str] = input,
    secret_fn: Callable[[str], str] = getpass.getpass,
    output_fn: Callable[[str], None] = print,
) -> Path:
    """Run the interactive setup wizard and atomically save a private env file."""
    path = config_path or Path(
        os.environ.get("LEMONO_DATA_DIR", "~/.lemono")
    ).expanduser() / ".env"
    existing = read_dotenv(path)
    provider = _choose_provider(input_fn, output_fn)
    label, key_name, default_model = PROVIDERS[provider]
    has_saved_key = bool(existing.get(key_name))
    key_hint = " (press Enter to keep saved key)" if has_saved_key else ""
    api_key = secret_fn(f"{label} API key{key_hint}: ").strip()
    if not api_key and not has_saved_key:
        raise ValueError("An API key is required / API 키가 필요합니다")
    if "\n" in api_key or "\r" in api_key:
        raise ValueError("API key must be a single line")

    model = input_fn(f"Default model [{default_model}]: ").strip() or default_model
    fallback = input_fn(
        "Fallback providers, comma-separated (optional) / 폴백 공급자 (선택): "
    ).strip()
    _safe_value(model, "model")
    _safe_value(fallback, "fallback providers")
    if fallback:
        unknown = [name for name in fallback.split(",") if name not in PROVIDERS]
        if unknown:
            raise ValueError(f"Unknown fallback provider: {', '.join(unknown)}")

    values = dict(existing)
    values.update(
        {
            "LEMONO_DEFAULT_PROVIDER": provider,
            "LEMONO_DEFAULT_MODEL": model,
            "LEMONO_FALLBACK_PROVIDERS": fallback,
        }
    )
    if api_key:
        values[key_name] = api_key
    _write_config(path, values)
    output_fn(f"\nSaved configuration to {path}")
    output_fn("Run `lemono --doctor` to verify it / 설정 확인: `lemono --doctor`")
    return path
